language: node_js
node_js:
  - "0.12"
  - "0.11"
  - "0.10"
  - "iojs"
  - "iojs-v1.0.4"
branches:
  only:
    - master

before_install:
  - npm update -g npm
  - npm install -g babel
  - npm install
